version: '3.8'

services:
  railway-py:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    container_name: railway-py
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs  # 如果需要日志持久化
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
